language: c
compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libcurl4-openssl-dev m4 wget autoconf libtool gfortran git

  ###
  # Install dependencies from a pre-built binary.
  ###
  - cd /
  - sudo wget http://www.unidata.ucar.edu/downloads/netcdf/ftp/travisdeps.tar.bz2
  - sudo tar -jxf travisdeps.tar.bz2
  - cd -

  # Install netcdf-c
  - git clone http://github.com/Unidata/netcdf-c
  - cd netcdf-c
  - mkdir build
  - cd build
  - cmake .. -DENABLE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/usr
  - make -j 4
  - sudo make install
  - cd ..
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j 4
  - make test
