sudo:false
language: c
compiler:
  - gcc

addons:
    apt:
      packages:
      - libcurl4-openssl-dev
      - m4
      - wget
      - autoconf
      - libtool
      - gfortran
      - git


before_install:


before_script:

  ###
  # Install dependencies from a pre-built binary.
  ###
  - cd $HOME
  - wget http://www.unidata.ucar.edu/downloads/netcdf/ftp/travisdeps_wnc.tar.bz2

  - tar -jxf travisdeps_wnc.tar.bz2
  - export LD_LIBRARY_PATH=$HOME/usr/lib
  - cd -
  ##
  # What to do to build.
  ##
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH=$HOME/usr

script:
  - make
  - make test
